use_frameworks!

platform :ios, '9.0'

target 'ChatBotLibrary' do
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end

target 'ChatBotLibrary_Example' do
  pod 'ChatBotLibrary', :path => '../'

  target 'ChatBotLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
